#!/usr/bin/env bash
# Assemble zdb.app for macOS. MUST run ON a Mac — cross-compiling gpui to macOS
# from Linux is not possible (Apple frameworks + Metal shader toolchain ship only
# with the macOS SDK / Xcode and are not redistributable). Builds natively for
# the host arch, then bundles the matching `sqls` binary next to the executable.
#
# Shipping the bare `zdb` executable is NOT enough: Finder cannot launch a Unix
# executable directly, so double-clicking it opens Terminal and runs the app from
# there, and it shows the generic executable icon. Only a .app bundle (Info.plist
# + CFBundleIconFile) launches silently with the real icon.
#
# Usage: scripts/package-macos.sh              (host arch)
#        scripts/package-macos.sh x86_64       (force Intel)
#
# Env:   ZDB_SKIP_BUILD=1   reuse an existing release binary instead of building
#        ZDB_ZIP=1          also write dist/zdb-macos-<arch>.zip via ditto, which
#                           preserves the exec bit and the bundle structure
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ARCH="${1:-$(uname -m)}"
case "$ARCH" in
    arm64|aarch64) ARCH=arm64;  RUST_TARGET=aarch64-apple-darwin; SQLS=sqls-darwin-arm64 ;;
    x86_64)        ARCH=x86_64; RUST_TARGET=x86_64-apple-darwin;  SQLS=sqls-darwin-amd64 ;;
    *) echo "unknown arch: $ARCH"; exit 1 ;;
esac

[ "$(uname -s)" = "Darwin" ] || { echo "ERROR: run this on macOS (native build only)"; exit 1; }

BIN="$ROOT/target/$RUST_TARGET/release/zdb"
if [ "${ZDB_SKIP_BUILD:-0}" = 1 ]; then
    # CI already ran a plain `cargo build --release`, which lands in target/release.
    [ -f "$BIN" ] || BIN="$ROOT/target/release/zdb"
    [ -f "$BIN" ] || { echo "ERROR: ZDB_SKIP_BUILD=1 but no release binary found"; exit 1; }
else
    echo "building zdb for $RUST_TARGET…"
    cargo build -p zdb-app --release --target "$RUST_TARGET"
fi

APP="$ROOT/dist/zdb.app"
MACOS="$APP/Contents/MacOS"
RESOURCES="$APP/Contents/Resources"
rm -rf "$APP"
mkdir -p "$MACOS" "$RESOURCES"

cp "$BIN" "$MACOS/zdb"
chmod +x "$MACOS/zdb"

# App icon — generated by scripts/gen-icon.py alongside the Windows .ico.
cp "$ROOT/crates/zdb-app/resources/zdb.icns" "$RESOURCES/zdb.icns"

# Bundle sqls next to the executable (zdb finds it there). Build it first if
# missing (Go cross-builds fine on any host).
[ -f "$ROOT/dist/sqls/$SQLS" ] || bash "$ROOT/scripts/build-sqls.sh"
if [ -f "$ROOT/dist/sqls/$SQLS" ]; then
    cp "$ROOT/dist/sqls/$SQLS" "$MACOS/sqls"
    chmod +x "$MACOS/sqls"
    echo "bundled sqls: $SQLS"
fi

cat > "$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>zdb</string>
  <key>CFBundleDisplayName</key><string>zdb</string>
  <key>CFBundleIdentifier</key><string>dev.zdb.app</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>zdb</string>
  <key>CFBundleIconFile</key><string>zdb.icns</string>
  <key>CFBundleIconName</key><string>zdb</string>
  <key>LSApplicationCategoryType</key><string>public.app-category.developer-tools</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSSupportsAutomaticGraphicsSwitching</key><true/>
</dict>
</plist>
EOF

# Ad-hoc signature. Apple Silicon refuses to run unsigned code, and every edit to
# the bundle (dropping in sqls, writing the plist) invalidates the signature the
# linker applied to the bare binary.
codesign --force --deep --sign - "$APP"
codesign --verify --deep --strict "$APP" && echo "ad-hoc signed"

# Nudge Launch Services: macOS caches a bundle's icon per path and will keep
# showing a stale (or generic) one otherwise.
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
    -f "$APP" >/dev/null 2>&1 || true
touch "$APP"

echo "built $APP"

if [ "${ZDB_ZIP:-0}" = 1 ]; then
    ZIP="$ROOT/dist/zdb-macos-$ARCH.zip"
    rm -f "$ZIP"
    ditto -c -k --sequesterRsrc --keepParent "$APP" "$ZIP"
    echo "wrote $ZIP"
fi
